---
#ANOTHER COMMENT
#This play installs apache on centos7
- name: Install Apache play
  hosts: web
  become: true

  tasks:
    - name: Install Apace
      yum:
        name: httpd
        state: latest

    - name: Start and enable service httpd, if not started
      service:
        name: httpd
        state: started
        enabled: true


    - name: Enable http service on firewall
      firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes  #reload firewalld if permanent
